from __future__ import annotations

import argparse
import json

from financial_forecast.clients.azure_llm_client import AzureLLMClient


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Send a single prompt to the Azure reasoning model."
    )

    parser.add_argument(
        "--message",
        default="gen-ai-response",
        help="Message value expected by the Azure endpoint.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.2,
        help="Sampling temperature.",
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=1024,
        help="Maximum output tokens.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=40,
        help="Top-k sampling parameter.",
    )
    parser.add_argument(
        "--raw",
        action="store_true",
        help="Print text response via ask_text() instead of JSON.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    client = AzureLLMClient()
    parameters = {
        "temperature": args.temperature,
        "max_tokens": args.max_tokens,
        "top_k": args.top_k,
    }

    if args.raw:
        response = client.ask_text(
            message=args.message,
            prompt=args.prompt,
            parameters=parameters,
            reasoning=True,
        )
        print(response)
        return

    prompt = """
  You are an elite Corporate Finance Advisor and Strategic Capital Expert at a top-tier investment bank. You specialize in advising the CEOs and CFOs of mature, cash-generative mega-cap technology firms on capital structure optimization, liquidity management, and capital allocation.
 
Context & Task:
I will provide you with two sets of financial data for a target company:
 
Historical Baseline: Actual financial performance from recent years.
 
ML Forecast: A multi-year financial forecast (Balance Sheet, Income Statement, and Cash Budget) generated by an advanced Monte Carlo machine learning ensemble.
 
Your task is to analyze the historical data against the forecast to identify the three most critical financial leverage points (risks or opportunities) over the forecasted period.
 
STRICT GUARDRAILS (CRITICAL):
 
NO OPERATIONAL ADVICE: You are strictly forbidden from recommending operational, marketing, or business strategy changes. Do not suggest "launching new products," "increasing sales efforts," or "improving supply chain efficiency."
 
STRICTLY FINANCIAL DOMAIN: Your recommendations must be confined purely to Corporate Finance: Capital Structure (debt/equity mix, WACC), Liquidity & Treasury (working capital, commercial paper), and Capital Allocation (dividends, share repurchases, CapEx).
 
MANDATORY EVIDENCE: You cannot make a claim without citing specific numbers from the provided tables.
 
Analytical Heuristics (The Mega-Cap Tech Lens & Trend Analysis):
 
Historical Benchmarking (Crucial): Always contextualize the forecast by comparing it to the historical baseline. Identify structural breaks (where the forecast deviates significantly from historical trends) or trend accelerations.
 
Strategic Leverage vs. Distress: Do not penalize shrinking Accounting Equity. If Equity is declining due to aggressive Stock Buybacks and Dividends, treat this as highly efficient Capital Return and WACC optimization—NOT financial distress—provided Net Income and Free Cash Flow remain historically strong.
 
Net Debt Focus: Evaluate liquidity by looking at Cash + Marketable Securities against Liabilities. Mega-cap tech companies often issue debt simply to lower their cost of capital; evaluate if the forecasted debt load is easily serviced by operating cash flows relative to historical interest coverage.
 
Operating Leverage: Note if the forecast predicts Revenue and Net Income growing at a faster or slower rate than historical Operating Expenses (OpEx).
 
Output Format:
Provide exactly 3 strategic priorities. For each, use this exact structure:
 
Observation: [State the specific quantitative trend, explicitly contrasting the forecasted figures against the historical baseline. Cite exact numbers and years].
 
Implication: [Explain the financial/credit risk or the WACC optimization opportunity this trend creates for the balance sheet].
 
Recommendation: [State the precise corporate finance action the CFO/CEO must execute to manage this specific trajectory].
 
Data Input:

Balance Sheet elements, with actual labels	2017	2018	2019	2020	2021	2022	2023	2024	2025
Assets		3.6573E+11	3.38516E+11	3.23888E+11	3.51002E+11	3.52755E+11	3.52583E+11	3.6498E+11	3.59241E+11
Non-current assets (Total Non Current Assets)		2.3439E+11	1.75697E+11	1.80175E+11	2.16166E+11	2.1735E+11	2.09017E+11	2.1199E+11	2.11284E+11
Advance payments for purchases (Other Current Assets)		1.2087E+10	12352000000	11264000000	14111000000	21223000000	14695000000	1.4287E+10	14585000000
Accounts receivables (Receivables)		4.8995E+10	45804000000	37445000000	51506000000	60932000000	60985000000	6.6243E+10	72957000000
Inventory (Inventory)	4855000000	3956000000	4106000000	4061000000	6580000000	4946000000	6331000000	7286000000	5718000000
Cash (Cash And Cash Equivalents)		2.5913E+10	48844000000	38016000000	34940000000	23646000000	29965000000	2.9943E+10	35934000000
Investment in market securities (Other Short Term Investments)		4.0388E+10	51713000000	52927000000	27699000000	24658000000	31590000000	3.5228E+10	18763000000
Liabilities									
Accounts payable (Accounts Payable)		5.5888E+10	46236000000	42296000000	54763000000	64115000000	62611000000	6.896E+10	69860000000
Advance payments from sales (Current Deferred Revenue)		5966000000	5522000000	6643000000	7612000000	7912000000	8061000000	8249000000	9055000000
Current liabilities (Total Current Liabilities - Accounts Payable - Current Deferred Revenue)		5.5012E+10	53960000000	56453000000	63106000000	81955000000	74636000000	9.9183E+10	86716000000
Non-current liabilities (Total Non Current Liabilities Net Minority Interest)		1.4171E+11	1.4231E+11	1.53157E+11	1.62431E+11	1.48101E+11	1.45129E+11	1.3164E+11	1.19877E+11
Equity									
Stockholders Equity		1.0715E+11	90488000000	65339000000	63090000000	50672000000	62146000000	5.695E+10	73733000000
Check		0	0	0	0	0	0	0	0
									
									
									
Income Statement elements of interest									
Sales (Total Revenue)		2.656E+11	2.60174E+11	2.74515E+11	3.65817E+11	3.94328E+11	3.83285E+11	3.9104E+11	4.16161E+11
Depreciation (Reconciled Depreciation)		1.0903E+10	12547000000	11056000000	11284000000	11104000000	11519000000	1.1445E+10	11698000000
COGS (Cost Of Revenue - Reconciled Depreciation)		1.5285E+11	1.49235E+11	1.58503E+11	2.01697E+11	2.12442E+11	2.02618E+11	1.9891E+11	2.09262E+11
OpEx (Operating Expense)		3.0941E+10	34462000000	38668000000	43887000000	51345000000	54847000000	5.7467E+10	62151000000
Income tax (Tax Provision)		1.3372E+10	10481000000	9680000000	14527000000	19300000000	16741000000	2.9749E+10	20719000000
Net Income		5.9531E+10	55256000000	57411000000	94680000000	99803000000	96995000000	9.3736E+10	1.1201E+11
									
									
									
									
Cash Flow elements of interest									
Dividends (Common Stock Dividend Paid)		1.3712E+10	14119000000	14081000000	14467000000	14841000000	15025000000	1.5234E+10	15421000000
Stock buyback (Repurchase of Capital Stock)		7.2738E+10	66897000000	72358000000	85971000000	89402000000	77550000000	9.4949E+10	90711000000


FORECAST BALANCE SHEET — Mean across Monte Carlo samples (USD)        
| Line Item | FY2025 | FY2026 | FY2027 | FY2028 | FY2029 | FY2030 | FY2031 | FY2032 | FY2033 | FY2034 |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| **ASSETS** |  |  |  |  |  |  |  |  |  |  |
| Non-Current Assets | $211,294,134,686 | $210,597,581,775 | $209,903,333,641 | $209,211,382,686 | $208,521,721,334 | $207,834,342,035 | $207,149,237,266 | $206,466,399,525 | $205,785,821,338 | $205,107,495,254 |
| Advance Payments (Purchases) | $16,374,224,975 | $16,890,984,352 | $17,292,784,103 | $17,655,445,055 | $17,979,604,046 | $18,265,980,509 | $18,515,372,659 | $18,728,653,189 | $18,906,764,530 | $19,050,713,718 |
| Accounts Receivable | $66,026,078,355 | $69,438,659,583 | $72,851,240,810 | $76,263,822,038 | $79,676,403,265 | $83,088,984,493 | $86,501,565,720 | $89,914,146,948 | $93,326,728,175 | $96,739,309,403 |       
| Inventory | $6,670,655,799 | $7,015,431,005 | $7,360,206,211 | $7,704,981,417 | $8,049,756,622 | $8,394,531,828 | $8,739,307,034 | $9,084,082,240 | $9,428,857,446 | $9,773,632,652 |
| Cash | $31,223,669,354 | $31,387,036,118 | $31,642,257,505 | $31,963,551,974 | $32,331,912,553 | $32,733,440,586 | $33,158,028,588 | $33,598,350,511 | $34,049,103,448 | $34,506,446,402 |
| Investment in Market Securities | $31,123,361,807 | $30,289,228,865 | $29,562,470,016 | $28,911,034,982 | $28,312,312,782 | $27,750,509,142 | $27,214,687,305 | $26,697,337,455 | $26,193,348,602 | $25,699,278,206 |
| TOTAL ASSETS | $362,712,124,977 | $365,618,921,698 | $368,612,292,286 | $371,710,218,151 | $374,871,710,602 | $378,067,788,593 | $381,278,198,571 | $384,488,969,867 | $387,690,623,539 | $390,876,875,635 |    
| **** |  |  |  |  |  |  |  |  |  |  |
| **LIABILITIES** |  |  |  |  |  |  |  |  |  |  |
| Accounts Payable | $64,316,968,943 | $66,346,768,633 | $67,925,013,842 | $69,349,524,208 | $70,622,801,190 | $71,747,670,678 | $72,727,268,012 | $73,565,021,081 | $74,264,631,697 | $74,830,055,432 |
| Advance Payments (Sales) | $8,846,925,987 | $9,304,182,488 | $9,761,438,989 | $10,218,695,489 | $10,675,951,990 | $11,133,208,491 | $11,590,464,992 | $12,047,721,492 | $12,504,977,993 | $12,962,234,494 |     
| Effective ST Debt | $87,204,056,424 | $96,117,022,855 | $105,620,475,218 | $115,735,721,110 | $126,483,234,187 | $137,882,470,325 | $149,951,679,605 | $162,707,716,402 | $176,165,850,080 | $190,339,579,048 | 
| Current LT Debt | $8,547,079,717 | $7,992,201,779 | $7,473,346,616 | $6,988,175,623 | $6,534,502,017 | $6,110,280,982 | $5,713,600,453 | $5,342,672,494 | $4,995,825,244 | $4,671,495,379 |
| Non-Current Liabilities | $123,108,130,835 | $115,115,929,056 | $107,642,582,440 | $100,654,406,817 | $94,119,904,800 | $88,009,623,818 | $82,296,023,365 | $76,953,350,871 | $71,957,525,628 | $67,286,030,248 |
| TOTAL LIABILITIES | $292,023,161,905 | $294,876,104,811 | $298,422,857,104 | $302,946,523,246 | $308,436,394,184 | $314,883,254,294 | $322,279,036,426 | $330,616,482,341 | $339,888,810,642 | $350,089,394,601 |
| **** |  |  |  |  |  |  |  |  |  |  |
| **EQUITY** |  |  |  |  |  |  |  |  |  |  |
| Equity | $70,688,963,072 | $70,742,816,887 | $70,189,435,182 | $68,763,694,904 | $66,435,316,418 | $63,184,534,300 | $58,999,162,146 | $53,872,487,527 | $47,801,812,898 | $40,787,481,034 |
| **** |  |  |  |  |  |  |  |  |  |  |
| TOTAL LIAB + EQUITY | $362,712,124,977 | $365,618,921,698 | $368,612,292,286 | $371,710,218,151 | $374,871,710,602 | $378,067,788,593 | $381,278,198,571 | $384,488,969,867 | $387,690,623,539 | $390,876,875,635 |
| CHECK: Assets-(L+E) | $-0 | $-0 | $-0 | $0 | $-0 | $-0 | $-0 | $0 | $-0 | $-0 |

FORECAST INCOME STATEMENT — Mean across Monte Carlo samples (USD)     
| Line Item | FY2025 | FY2026 | FY2027 | FY2028 | FY2029 | FY2030 | FY2031 | FY2032 | FY2033 | FY2034 |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Revenue (Sales_t) | $416,161,000,000 | $437,670,428,571 | $459,179,857,143 | $480,689,285,714 | $502,198,714,286 | $523,708,142,857 | $545,217,571,429 | $566,727,000,000 | $588,236,428,571 | $609,745,857,143 |
| COGS | $209,479,943,818 | $215,111,448,777 | $220,236,683,361 | $224,862,675,415 | $228,997,548,241 | $232,650,478,706 | $235,831,648,594 | $238,552,189,724 | $240,824,123,455 | $242,660,295,213 |
| OpEx | $59,189,357,476 | $62,743,853,543 | $66,268,928,527 | $69,970,096,920 | $73,867,187,499 | $77,530,912,397 | $81,309,330,879 | $85,303,190,906 | $89,343,258,569 | $93,310,113,709 |
| Depreciation & Amortization | $11,772,820,547 | $11,734,009,756 | $11,695,327,383 | $11,656,773,003 | $11,618,346,194 | $11,580,046,536 | $11,541,873,610 | $11,503,826,998 | $11,465,906,283 | $11,428,111,049 |
| EBIT = Revenue - COGS - OpEx - Depreciation | $135,718,878,159 | $148,081,116,495 | $160,978,917,872 | $174,199,740,376 | $187,715,632,351 | $201,946,705,217 | $216,534,718,346 | $231,367,792,372 | $246,603,140,266 | $262,347,337,172 |
| Interest Payments | $4,494,432,488 | $4,376,763,861 | $4,672,141,362 | $4,994,830,605 | $5,345,430,056 | $5,724,521,177 | $6,132,660,059 | $6,570,368,970 | $7,038,127,887 | $7,536,366,110 |
| ST Investment Returns | $247,941,789 | $219,052,515 | $213,181,719 | $208,066,643 | $203,481,711 | $199,267,783 | $195,313,696 | $191,542,473 | $187,901,260 | $184,354,085 |
| EBT = EBIT - Interest + ST Returns | $131,472,387,460 | $143,923,405,149 | $156,519,958,229 | $169,412,976,414 | $182,573,684,006 | $196,421,451,823 | $210,597,371,983 | $224,988,965,875 | $239,752,913,638 | $254,995,325,146 |
| Income Taxes = EBT * %EffTax (15.51%) | $20,396,751,105 | $22,328,413,819 | $24,282,655,032 | $26,282,890,123 | $28,324,654,803 | $30,473,010,660 | $32,672,276,382 | $34,905,001,932 | $37,195,494,816 | $39,560,217,019 |
| Net Income = EBT - Income Taxes | $111,075,636,355 | $121,594,991,330 | $132,237,303,196 | $143,130,086,291 | $154,249,029,203 | $165,948,441,164 | $177,925,095,601 | $190,083,963,943 | $202,557,418,823 | $215,435,108,127 |
| Dividends | $15,525,131,801 | $15,879,492,946 | $16,271,553,727 | $16,701,630,303 | $17,170,510,589 | $17,678,889,409 | $18,228,773,075 | $18,821,035,846 | $19,456,196,296 | $20,135,262,019 |

    """

    response = client.ask_json(
        message=args.message,
        prompt=prompt,
        parameters=parameters,
        reasoning=True,
    )
    # print(json.dumps(response, indent=2, ensure_ascii=False))
    print(response["raw_response"])


if __name__ == "__main__":
    main()
