"""Abstract and concrete advisor classes for LLM-based CEO recommendations.

Provides a base class :class:`Advisor` that defines the interface for
sending a financial report to an LLM and printing its response, and a
concrete :class:`DeepseekCEOAdvisor` that uses the Azure DeepSeek endpoint.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Dict


class Advisor(ABC):
    """Abstract base class for LLM-powered financial advisors.

    Subclasses implement :meth:`build_prompt` to construct the system
    prompt and :meth:`recommend` to send it and return the response.
    This allows swapping the LLM backend (Azure, OpenAI, local) or
    the advisory persona without changing the report pipeline.
    """

    @abstractmethod
    def build_prompt(
        self,
        historical_table: str,
        forecast_table: str,
    ) -> str:
        """Combine formatted tables into a full LLM prompt.

        Args:
            historical_table: Formatted historical data.
            forecast_table: Formatted forecast data.

        Returns:
            Complete prompt string ready to send.
        """

    @abstractmethod
    def recommend(self, prompt: str) -> str:
        """Send the prompt to the LLM and return the response text.

        Args:
            prompt: The full analyst prompt.

        Returns:
            LLM response as a string.
        """


class DeepseekCEOAdvisor(Advisor):
    """CEO/CFO advisor backed by the Azure DeepSeek reasoning model.

    Encapsulates the prompt template, Azure client configuration, and
    model parameters.  Call :meth:`recommend` to get strategic
    recommendations from the LLM.

    Args:
        message: Message label for the Azure endpoint.
        parameters: Dict of model sampling parameters
            (``temperature``, ``max_tokens``, ``top_k``).
        raw: If ``True``, use ``ask_text`` instead of ``ask_json``.
    """

    _PROMPT_TEMPLATE = """
You are an elite Corporate Finance Advisor and Strategic Capital Expert at a top-tier investment bank. You specialize in advising the CEOs and CFOs of mature, cash-generative mega-cap technology firms on capital structure optimization, liquidity management, and capital allocation.

Context & Task:
I will provide you with two sets of financial data for a target company:

Historical Baseline: Actual financial performance from recent years.

ML Forecast: A multi-year financial forecast (Balance Sheet, Income Statement, and Cash Budget) generated by an advanced Monte Carlo machine learning ensemble.

Your task is to analyze the historical data against the forecast to identify the three most critical financial leverage points (risks or opportunities) over the forecasted period.

STRICT GUARDRAILS (CRITICAL):

NO OPERATIONAL ADVICE: You are strictly forbidden from recommending operational, marketing, or business strategy changes. Do not suggest "launching new products," "increasing sales efforts," or "improving supply chain efficiency."

STRICTLY FINANCIAL DOMAIN: Your recommendations must be confined purely to Corporate Finance: Capital Structure (debt/equity mix, WACC), Liquidity & Treasury (working capital, commercial paper), and Capital Allocation (dividends, share repurchases, CapEx).

MANDATORY EVIDENCE: You cannot make a claim without citing specific numbers from the provided tables.

Analytical Heuristics (The Mega-Cap Tech Lens & Trend Analysis):

Historical Benchmarking (Crucial): Always contextualize the forecast by comparing it to the historical baseline. Identify structural breaks (where the forecast deviates significantly from historical trends) or trend accelerations.

Strategic Leverage vs. Distress: Do not penalize shrinking Accounting Equity. If Equity is declining due to aggressive Stock Buybacks and Dividends, treat this as highly efficient Capital Return and WACC optimization—NOT financial distress—provided Net Income and Free Cash Flow remain historically strong.

Net Debt Focus: Evaluate liquidity by looking at Cash + Marketable Securities against Liabilities. Mega-cap tech companies often issue debt simply to lower their cost of capital; evaluate if the forecasted debt load is easily serviced by operating cash flows relative to historical interest coverage.

Operating Leverage: Note if the forecast predicts Revenue and Net Income growing at a faster or slower rate than historical Operating Expenses (OpEx).

Output Format:
Provide exactly 3 strategic priorities. For each, use this exact structure:

Observation: [State the specific quantitative trend, explicitly contrasting the forecasted figures against the historical baseline. Cite exact numbers and years].

Implication: [Explain the financial/credit risk or the WACC optimization opportunity this trend creates for the balance sheet].

Recommendation: [State the precise corporate finance action the CFO/CEO must execute to manage this specific trajectory].

Data Input:

{historical_table}

{forecast_table}
"""

    def __init__(
        self,
        message: str = "gen-ai-response",
        parameters: Dict[str, Any] | None = None,
        raw: bool = False,
    ):
        self._message = message
        self._parameters = parameters or {
            "temperature": 0.2,
            "max_tokens": 100000,
            "top_k": 40,
        }
        self._raw = raw

    def build_prompt(
        self,
        historical_table: str,
        forecast_table: str,
    ) -> str:
        return self._PROMPT_TEMPLATE.format(
            historical_table=historical_table,
            forecast_table=forecast_table,
        )

    def recommend(self, prompt: str) -> str:
        from financial_forecast.clients.azure_llm_client import AzureLLMClient

        client = AzureLLMClient()

        if self._raw:
            return client.ask_text(
                message=self._message,
                prompt=prompt,
                parameters=self._parameters,
                reasoning=True,
            )

        response = client.ask_json(
            message=self._message,
            prompt=prompt,
            parameters=self._parameters,
            reasoning=True,
        )
        return response["raw_response"]
